export type Category =
  | 'presence'
  | 'everyday'
  | 'gratitude'
  | 'joy'
  | 'strength'
  | 'family'
  | 'beauty'
  | 'character'
  | 'devotion'
  | 'mind'
  | 'resilience'
  | 'warmth'
  | 'partnership'
  | 'admiration'
  | 'tenderness'
  | 'humor'
  | 'wisdom'
  | 'growth'
  | 'sanctuary'
  | 'legacy';

export interface Compliment {
  text: string;
  category: Category;
}

export const compliments: Compliment[] = [
  // ── Original 25 ──────────────────────────────────────────────────────────
  { text: "The way you move through a room — I still notice it like the first time.", category: "presence" },
  { text: "You make ordinary days feel like something worth remembering.", category: "everyday" },
  { text: "I'm a better man because you chose me.", category: "gratitude" },
  { text: "Your laugh is the best sound in this house.", category: "joy" },
  { text: "You handle hard things with so much grace. I see it, even when you don't.", category: "strength" },
  { text: "The way you love our kids — it floors me.", category: "family" },
  { text: "You are genuinely beautiful. Not just to me — to everyone in the room.", category: "beauty" },
  { text: "I don't take for granted what it feels like to come home to you.", category: "gratitude" },
  { text: "You have this way of making people feel seen. It's a rare gift.", category: "character" },
  { text: "I'd choose you again. Every single time.", category: "devotion" },
  { text: "The life we're building together — you're the reason it's good.", category: "everyday" },
  { text: "You are more capable than you give yourself credit for.", category: "strength" },
  { text: "Your heart is one of the most beautiful things about you.", category: "character" },
  { text: "I love the way your mind works — how you see things I would have missed.", category: "mind" },
  { text: "You make me want to be more present. You deserve that.", category: "devotion" },
  { text: "Thank you for carrying so much, so quietly.", category: "gratitude" },
  { text: "You are someone worth fighting for. I never forget that.", category: "devotion" },
  { text: "The kindness you show without thinking — it's one of my favorite things about you.", category: "character" },
  { text: "I feel lucky. Still. After everything.", category: "gratitude" },
  { text: "When you walk into a room, it's still you I look for first.", category: "presence" },
  { text: "You are exactly who our family needed.", category: "family" },
  { text: "Your strength doesn't make you hard — it makes you extraordinary.", category: "strength" },
  { text: "I'm proud to be your husband.", category: "devotion" },
  { text: "You bring warmth into every space you enter.", category: "presence" },
  { text: "The way you care for people — it's one of the things I admire most.", category: "character" },

  // ── 340 New ───────────────────────────────────────────────────────────────
  { text: "The way you sit quietly in the morning, hands wrapped around your coffee — I could watch that forever.", category: "presence" },
  { text: "You folded the laundry again without saying anything. I noticed.", category: "everyday" },
  { text: "Thank you for saying yes. To me. To this life. To all of it.", category: "gratitude" },
  { text: "You laughed at something today and the whole room shifted.", category: "joy" },
  { text: "You don't quit. Not when it's hard, not when no one's watching. That's not nothing.", category: "strength" },
  { text: "The way you talk to our kids when they're scared — you know exactly what they need.", category: "family" },
  { text: "You have no idea how good you look in the morning light.", category: "beauty" },
  { text: "Your integrity shows up in the small things. That's where it counts.", category: "character" },
  { text: "I still reach for you in the dark. That hasn't changed.", category: "devotion" },
  { text: "You connected dots I didn't even know existed. Your mind moves differently — I mean that as the highest compliment.", category: "mind" },
  { text: "You've survived things that would have broken other people. You just kept going.", category: "resilience" },
  { text: "You make this house feel like somewhere people want to be.", category: "warmth" },
  { text: "You pick up what I drop without making me feel like I dropped it.", category: "partnership" },
  { text: "Watching you in your element is one of my quiet pleasures.", category: "admiration" },
  { text: "The way you hold me when I'm low — you don't say a word and somehow that's everything.", category: "tenderness" },
  { text: "You made me laugh until I couldn't breathe last week. I keep thinking about it.", category: "humor" },
  { text: "You said one sentence that reframed everything. You do that more than you know.", category: "wisdom" },
  { text: "The person you've become — I watched it happen and I'm still amazed.", category: "growth" },
  { text: "Coming home to you is the best part of every day. Not a small thing.", category: "sanctuary" },
  { text: "What you're building — who you're shaping, what you're modeling — it will outlast both of us.", category: "legacy" },
  { text: "You have a stillness about you sometimes that makes everything slow down.", category: "presence" },
  { text: "You remembered something I mentioned once, months ago, and showed up for it. That's you.", category: "everyday" },
  { text: "I don't say it enough — thank you for trusting me with your heart.", category: "gratitude" },
  { text: "Your happiness is contagious. I catch it every time.", category: "joy" },
  { text: "You are tougher than you think and softer than you let on. Both are true.", category: "strength" },
  { text: "You're teaching our kids things I couldn't put into words. They're learning it just by watching you.", category: "family" },
  { text: "The way your eyes look when you're genuinely happy — I'd do a lot to see that.", category: "beauty" },
  { text: "You keep your word. Every time. People remember that.", category: "character" },
  { text: "I think about you during the day for no particular reason. Just do.", category: "devotion" },
  { text: "You asked the question nobody else thought to ask. That's a kind of intelligence most people never develop.", category: "mind" },
  { text: "You've rebuilt yourself more than once. Quietly. Without asking for applause.", category: "resilience" },
  { text: "You have a gift for making people feel welcome without even trying.", category: "warmth" },
  { text: "We make a good team. I don't say that enough.", category: "partnership" },
  { text: "The competence you carry — the way you just handle things — I find it deeply attractive.", category: "admiration" },
  { text: "You checked in on me when I didn't even know I needed it.", category: "tenderness" },
  { text: "You have a sense of humor that catches me off guard every time. I love that about you.", category: "humor" },
  { text: "You don't give advice until you've actually thought about it. That's rare.", category: "wisdom" },
  { text: "The woman you are now compared to who you were — you've done real work on yourself. It shows.", category: "growth" },
  { text: "When things fall apart, I still want to be next to you. That says everything.", category: "sanctuary" },
  { text: "The values you live by — our kids are going to carry those long after we're gone.", category: "legacy" },
  { text: "You're fully here when you're here. That's not as common as it should be.", category: "presence" },
  { text: "You made dinner after a brutal day and didn't mention either. I saw that.", category: "everyday" },
  { text: "Thank you for forgiving me when I didn't deserve it. I haven't forgotten.", category: "gratitude" },
  { text: "You find joy in things that most people walk past. I've started seeing them too, because of you.", category: "joy" },
  { text: "You hold the line when it matters. You don't waver. That's a kind of strength I genuinely respect.", category: "strength" },
  { text: "You show up for our family in ways they won't fully appreciate until they're older.", category: "family" },
  { text: "You got dressed and walked out the door and I just stood there for a second.", category: "beauty" },
  { text: "You don't talk about people behind their backs. I've noticed. It says a lot.", category: "character" },
  { text: "Even when I'm frustrating, you stay. That means more than you know.", category: "devotion" },
  { text: "You understand things intuitively that take most people years to learn.", category: "mind" },
  { text: "You lost something real this year and you grieved it with grace and then you kept going.", category: "resilience" },
  { text: "You always know when someone in the room needs a little more warmth. And you give it.", category: "warmth" },
  { text: "You cover for me without making me feel small. That's a skill and a kindness.", category: "partnership" },
  { text: "I brag about you to people who don't even know you. Can't help it.", category: "admiration" },
  { text: "The way you touch my face when you're trying to say something you can't quite find words for.", category: "tenderness" },
  { text: "You were funnier than everyone in the room last night. I was so proud.", category: "humor" },
  { text: "You knew something was off before anyone else did. You trusted that instinct. You were right.", category: "wisdom" },
  { text: "You're not who you were five years ago — you're better. You did that on purpose.", category: "growth" },
  { text: "There is nowhere I feel more like myself than next to you.", category: "sanctuary" },
  { text: "The way you love — it will ripple further than you can imagine.", category: "legacy" },
  { text: "You're present in a way that makes people feel like they're the only one in the room.", category: "presence" },
  { text: "You ran an errand I forgot I mentioned needing. You didn't bring it up. You just did it.", category: "everyday" },
  { text: "Thank you for being honest with me even when it wasn't easy. It made us stronger.", category: "gratitude" },
  { text: "The delight you take in small things — a good meal, a song you love, the first cold morning of fall — it's infectious.", category: "joy" },
  { text: "You stay calm when everyone else is spinning out. That calm is a form of leadership.", category: "strength" },
  { text: "You remember the small details of our kids' lives that I'd have let slip. That matters.", category: "family" },
  { text: "There's something about the way you smile when you don't mean to — when something catches you off guard — that I live for.", category: "beauty" },
  { text: "You said no to something that would have been easy to say yes to. That took character.", category: "character" },
  { text: "I'm not a complete person without you. That's just the truth.", category: "devotion" },
  { text: "You synthesized three complicated things into one clear thought. I've been thinking about it ever since.", category: "mind" },
  { text: "You've been tired for a long time and you're still showing up. I don't take that lightly.", category: "resilience" },
  { text: "People leave your presence feeling better about themselves. That's a meaningful thing to be.", category: "warmth" },
  { text: "You course-correct without making a scene. I try to learn from that.", category: "partnership" },
  { text: "You're good at what you do in a way that's obvious to everyone but you.", category: "admiration" },
  { text: "You put your hand on my chest when I was worried. Just rested it there. I stopped worrying.", category: "tenderness" },
  { text: "You told a story last night that had everyone at the table leaning in. You're a natural.", category: "humor" },
  { text: "You don't mistake motion for progress. You know the difference — and act accordingly.", category: "wisdom" },
  { text: "You've let go of things that were holding you back. That's harder than people think.", category: "growth" },
  { text: "After a hard week, you're still the place I most want to be.", category: "sanctuary" },
  { text: "The example you're setting — it's already in them. You can't see it yet, but it's there.", category: "legacy" },
  { text: "You pay attention. Real attention. It makes people feel seen, and it makes me feel chosen.", category: "presence" },
  { text: "You refilled my water without me asking. Nobody saw that but me.", category: "everyday" },
  { text: "Thank you for building this life with me like it was worth building. It is.", category: "gratitude" },
  { text: "Watching you enjoy something you love — your whole face changes. I don't get tired of that.", category: "joy" },
  { text: "You've carried weight this year that would buckle most people. You made it look manageable. It wasn't.", category: "strength" },
  { text: "The rituals you've created for our family — the small ones — those are the things they'll remember.", category: "family" },
  { text: "You look remarkable without trying. Even more remarkable when you do.", category: "beauty" },
  { text: "You treat people the same whether it benefits you or not. That's a hard thing to fake — and you're not faking it.", category: "character" },
  { text: "I still get something that feels like nervous excitement when I know I'm about to see you.", category: "devotion" },
  { text: "The way your mind makes unexpected connections — you see the world differently and it's made me see it better.", category: "mind" },
  { text: "You don't pretend things are fine when they're not. You face them. That's a quiet kind of courage.", category: "resilience" },
  { text: "You make strangers feel like they're not strangers for long.", category: "warmth" },
  { text: "You tell me hard truths in a way I can actually hear. That's a real skill — and a real act of love.", category: "partnership" },
  { text: "I love watching you own a room. You don't even know you're doing it.", category: "admiration" },
  { text: "You knew I needed space before I did. You gave it without making me ask.", category: "tenderness" },
  { text: "You have a line for every situation. I never know when it's coming and it gets me every time.", category: "humor" },
  { text: "You don't react to everything. You choose when to engage. That's a kind of wisdom that takes years to develop.", category: "wisdom" },
  { text: "You're curious in a way that keeps you growing. I find that genuinely beautiful.", category: "growth" },
  { text: "You are my soft place to land. I've never had that before you.", category: "sanctuary" },
  { text: "The kindness you're pouring into the next generation — it won't stop with them.", category: "legacy" },
  { text: "When you're in the room, I'm more aware of the room. And of myself.", category: "presence" },
  { text: "You made the bed again. Small thing. Not small to me.", category: "everyday" },
  { text: "Thank you for staying through the version of me that was harder to love. It meant everything.", category: "gratitude" },
  { text: "You get excited about things in a way that makes the thing more exciting. I catch it every time.", category: "joy" },
  { text: "You don't wait to be rescued. You handle it — and then sometimes let me help. I appreciate the order of that.", category: "strength" },
  { text: "You protect our kids without hovering. That balance is harder than it looks.", category: "family" },
  { text: "The way you look when you're laughing at something — uninhibited, full — that's the most beautiful version of you.", category: "beauty" },
  { text: "You own your mistakes instead of explaining them away. That's rarer than it should be.", category: "character" },
  { text: "I still choose this — you, us, the whole complicated beautiful thing. Every day I choose it.", category: "devotion" },
  { text: "You read the room in a way I'm still trying to learn. It's a quiet intelligence.", category: "mind" },
  { text: "You didn't collapse when you had every right to. I was watching and I was in awe.", category: "resilience" },
  { text: "You fill silence with the right thing — sometimes nothing, sometimes everything. You know which.", category: "warmth" },
  { text: "You advocate for our family without fanfare. Just quietly, firmly, always.", category: "partnership" },
  { text: "I catch myself wanting to tell you things just to watch you react to them. Your reactions are one of my favorite things.", category: "admiration" },
  { text: "The way you reached for my hand during that hard conversation — I felt it for days.", category: "tenderness" },
  { text: "You found the comedy in something that had no business being funny. And you were right.", category: "humor" },
  { text: "You have a long view that most people don't. You see where things are going before they arrive.", category: "wisdom" },
  { text: "The risks you've taken on yourself — to grow, to change — they've paid off. You can see it.", category: "growth" },
  { text: "The world makes more sense when I can talk to you at the end of the day.", category: "sanctuary" },
  { text: "The love you're putting into this life is building something that will matter long after us.", category: "legacy" },
  { text: "You make people feel like time slows down around you. I know that feeling well.", category: "presence" },
  { text: "You noticed the thing that needed doing and just did it. No announcement, no credit. That's character.", category: "everyday" },
  { text: "Thank you for the thousand small ways you make my life easier that I haven't thanked you for.", category: "gratitude" },
  { text: "You made something ordinary feel like a celebration just by being excited about it.", category: "joy" },
  { text: "You don't need validation to feel solid. You know who you are. That's a kind of strength that's hard to cultivate.", category: "strength" },
  { text: "The consistency of your love for our kids — no matter the season, no matter the difficulty — it's one of the most reliable things in their lives.", category: "family" },
  { text: "Something about the way you looked last night stopped me mid-thought.", category: "beauty" },
  { text: "You take responsibility without being dramatic about it. You just fix things and move forward.", category: "character" },
  { text: "I have loved you in hard seasons and easy ones and I would not trade any of it.", category: "devotion" },
  { text: "The clarity of your thinking under pressure is remarkable. You get sharper when others get foggy.", category: "mind" },
  { text: "You rebuilt after loss without losing what made you you. That's not easy and not everyone does it.", category: "resilience" },
  { text: "You carry warmth in you that comes out whether you intend it or not. It's just part of how you're made.", category: "warmth" },
  { text: "You are the best decision I've ever made. I'd make it again with everything I know now.", category: "partnership" },
  { text: "I'm proud of you — not for any one thing, but for the overall shape of who you are.", category: "admiration" },
  { text: "You remembered to ask about the thing I was worried about three days ago. That's a kind of care that doesn't go unnoticed.", category: "tenderness" },
  { text: "You laughed at yourself with zero self-consciousness. That kind of ease is genuinely attractive.", category: "humor" },
  { text: "You've taught me things about patience that I couldn't have learned anywhere else.", category: "wisdom" },
  { text: "You've grown in the hard places, not just the comfortable ones. That's how the best growth works.", category: "growth" },
  { text: "With you, quiet is never empty. It's one of my favorite things about us.", category: "sanctuary" },
  { text: "The loyalty you pour into the people you love — it's a form of legacy already in motion.", category: "legacy" },
  { text: "You're fully in the moment in a way that makes the moment feel worth being in.", category: "presence" },
  { text: "You picked up the dry cleaning on a week that was already too full. I didn't ask. You just did it.", category: "everyday" },
  { text: "Thank you for being someone I can disappoint and still feel safe with.", category: "gratitude" },
  { text: "You find something worth laughing about in almost any day. I've started doing it too because of you.", category: "joy" },
  { text: "You ask for what you need. That took strength and I appreciate it.", category: "strength" },
  { text: "You show up to the small moments of our kids' lives like they're the important ones. They are.", category: "family" },
  { text: "The way you dress when you feel good — I feel it across a room.", category: "beauty" },
  { text: "You don't gossip. You just don't. In a world that does, that stands out.", category: "character" },
  { text: "I love you in the full sense — not just fondly, but deeply, deliberately, durably.", category: "devotion" },
  { text: "You see the logic underneath the emotion in a situation. That's not easy to do — and you do it reliably.", category: "mind" },
  { text: "You've had the rug pulled out more than once. You got up. Every single time.", category: "resilience" },
  { text: "You make the people around you feel warmer — not just comfortable, but actually warmer.", category: "warmth" },
  { text: "We've built something real together. That doesn't happen by accident. You did that too.", category: "partnership" },
  { text: "The way you talk about your work — the precision, the investment — I never get tired of watching you in that mode.", category: "admiration" },
  { text: "You leave things better than you found them — rooms, conversations, people.", category: "tenderness" },
  { text: "Your laugh when something really gets you — full and unguarded — is one of the best sounds I know.", category: "humor" },
  { text: "You've learned what to hold and what to let go. That's taken real discernment.", category: "wisdom" },
  { text: "You've leaned into the uncomfortable stuff because you knew it would make you better. I've seen that up close.", category: "growth" },
  { text: "When I'm with you, I don't need to be anywhere else. That's a rare kind of peace.", category: "sanctuary" },
  { text: "The love you've planted in your people — it's already growing in directions you can't see.", category: "legacy" },
  { text: "You're engaged in a way that makes conversations feel like they actually matter.", category: "presence" },
  { text: "You stayed up to make sure I had what I needed even though you were exhausted. I saw the light under the door.", category: "everyday" },
  { text: "Thank you for choosing this life with me, even on the days the choice costs something.", category: "gratitude" },
  { text: "Your happiness, when it's full and real, is one of the things I most want to protect.", category: "joy" },
  { text: "You don't outsource your hard feelings. You sit with them and come out the other side with something real.", category: "strength" },
  { text: "The way our kids look at you — like you're safe, like you're certain — that's everything.", category: "family" },
  { text: "You look like yourself. Entirely. Nobody else could wear that face.", category: "beauty" },
  { text: "You handle criticism with a composure that most people never develop.", category: "character" },
  { text: "If this is the only life I get, spending it with you feels like I got the thing right.", category: "devotion" },
  { text: "You ask better questions than most people have answers to.", category: "mind" },
  { text: "Watching you navigate the worst year of your life without losing who you are — that's something I won't forget.", category: "resilience" },
  { text: "The way you take care of the people in your orbit — quietly, without keeping score — it's one of your most beautiful qualities.", category: "warmth" },
  { text: "We don't agree on everything and that's part of why this works.", category: "partnership" },
  { text: "You handle the things you're best at with such ease — and I know how much work went into that ease.", category: "admiration" },
  { text: "You put your hand on my back when we walked in. You do that every time. I always notice.", category: "tenderness" },
  { text: "You laughed at something absurd with me at midnight and that's one of my favorite memories of this year.", category: "humor" },
  { text: "You play the long game in the ways that actually matter. That's wisdom with patience behind it.", category: "wisdom" },
  { text: "You keep becoming someone I didn't expect and somehow it's always better.", category: "growth" },
  { text: "You are my home in every sense of that word.", category: "sanctuary" },
  { text: "The mark you're leaving on people — on the kids, on your friends, on me — is a real one.", category: "legacy" },
  { text: "There's a quality in how you move through the world — unhurried, purposeful — that I find steadying.", category: "presence" },
  { text: "You made the appointment I kept forgetting. You didn't mention it. Just sent me the reminder.", category: "everyday" },
  { text: "I am grateful for you in a way that I feel in my chest, not just in my head.", category: "gratitude" },
  { text: "You bring lightness into rooms that need it. People gravitate toward that even if they can't name it.", category: "joy" },
  { text: "You've said hard things to me because you loved me too much to stay quiet. I needed that.", category: "strength" },
  { text: "You create a sense of security in our home that I didn't even know to ask for.", category: "family" },
  { text: "You have an elegance that's yours and nobody else's. I can't explain it better than that.", category: "beauty" },
  { text: "You didn't choose the easy path when the right path was harder. I've seen that more than once.", category: "character" },
  { text: "The love I have for you has changed shape over the years. It's bigger now. Deeper. More certain.", category: "devotion" },
  { text: "You think in systems. You see how parts connect into wholes. That's not a common way to see the world.", category: "mind" },
  { text: "You've faced things that had no good options. You made the best one available and didn't complain about the cost.", category: "resilience" },
  { text: "You make people feel like their problems are worth caring about. Because to you, they are.", category: "warmth" },
  { text: "You catch me before I fall and somehow you make it feel like I caught myself.", category: "partnership" },
  { text: "Watching you do the things you're good at is genuinely one of my pleasures in life.", category: "admiration" },
  { text: "The way you talk to me when I'm low — careful, steady — I come back to those words.", category: "tenderness" },
  { text: "You found the absurdity in something awful and gave us all permission to laugh. That's a gift.", category: "humor" },
  { text: "You know when something is worth the fight and when it isn't. That discernment has saved us both.", category: "wisdom" },
  { text: "The stretch and difficulty of the last few years have made you more — not less. I see that.", category: "growth" },
  { text: "You make uncertainty feel survivable. That's not a small thing to give someone.", category: "sanctuary" },
  { text: "You are going to be remembered by the people who matter most. That's already true.", category: "legacy" },
  { text: "You're at home in yourself in a way that makes you easy to be around.", category: "presence" },
  { text: "You leave things organized so I can find them. You don't tell me you do it. You just do.", category: "everyday" },
  { text: "Thank you for the grace you've shown me in the seasons when I was harder to reach.", category: "gratitude" },
  { text: "Something in the way you experience joy is contagious in the best possible way.", category: "joy" },
  { text: "You are steadier than you think. The people around you depend on that steadiness.", category: "strength" },
  { text: "You make space for our kids to be themselves, not smaller versions of who we wanted.", category: "family" },
  { text: "You are a beautiful human being. I'm not saying it to say it — I mean it every time.", category: "beauty" },
  { text: "You give honest answers to hard questions. Not performing honesty — actually being honest. There's a difference.", category: "character" },
  { text: "I would make every hard choice again if it led me back to a life with you in it.", category: "devotion" },
  { text: "You think before you speak and you mean what you say. Both matter more than people realize.", category: "mind" },
  { text: "You've been asked to be strong for too long in some seasons. You did it anyway. I saw the cost.", category: "resilience" },
  { text: "You hold space for people's hard things without trying to fix what isn't fixable. That's rare and it's healing.", category: "warmth" },
  { text: "We've gotten better at this — at being married — and that's both of us working.", category: "partnership" },
  { text: "You've earned everything I admire about you. None of it was given.", category: "admiration" },
  { text: "The look you gave me across the room at that party said more than an hour of conversation.", category: "tenderness" },
  { text: "Your sense of humor has an edge to it that I find completely irresistible.", category: "humor" },
  { text: "You've gotten better at trusting your own judgment. That's taken real work to get there.", category: "wisdom" },
  { text: "You invest in yourself the same way you invest in the people you love. That took a while. I'm glad you're there.", category: "growth" },
  { text: "When life gets loud, you are still the quietest, surest thing I can orient toward.", category: "sanctuary" },
  { text: "The love you give — it doesn't stop at the edges of this family. It keeps going.", category: "legacy" },
  { text: "You listen with your whole face. People feel heard by you before you even respond.", category: "presence" },
  { text: "You stocked the house before a hard week without making a thing of it. That's love in logistics.", category: "everyday" },
  { text: "Thank you for making sacrifices quietly and without keeping a tab. I see them.", category: "gratitude" },
  { text: "You can turn the most mundane Saturday into something worth keeping.", category: "joy" },
  { text: "You've absorbed chaos this year and transformed it into something manageable. That is a real and difficult strength.", category: "strength" },
  { text: "You love our family in a way that costs you something. I want you to know I understand that.", category: "family" },
  { text: "There are moments when I look at you and think — how did I get this lucky.", category: "beauty" },
  { text: "You don't let people off the hook when something matters. You hold a standard. I find that admirable.", category: "character" },
  { text: "We have built something worth protecting. You are most of why.", category: "devotion" },
  { text: "You read between the lines — in people, in situations, in conversations. That's a subtle intelligence.", category: "mind" },
  { text: "You bent without breaking in a year that asked a lot of you. Bending without breaking is its own kind of strength.", category: "resilience" },
  { text: "The way you keep track of the people you love — checking in, showing up, remembering — you're a net of warmth.", category: "warmth" },
  { text: "You've shouldered things that weren't yours to carry and done it without resentment. That's extraordinary.", category: "partnership" },
  { text: "I have watched you handle things I could not have handled. I think about that.", category: "admiration" },
  { text: "You pulled me close without a word when I needed it most. You knew before I did.", category: "tenderness" },
  { text: "You are genuinely funny — not performatively, but from some actual place of joy and timing.", category: "humor" },
  { text: "You've earned the right to trust yourself through real experience. I've watched you do the work.", category: "wisdom" },
  { text: "You have done the hard thing of actually changing. Not talking about it. Doing it.", category: "growth" },
  { text: "You make the life we've built feel like enough. More than enough.", category: "sanctuary" },
  { text: "You are already someone's reason for doing it differently. Probably more than one someone.", category: "legacy" },
  { text: "You have a presence that fills whatever space you're in — not loudly, but completely.", category: "presence" },
  { text: "You took something off my plate today without making me feel like I needed help. That's a skill.", category: "everyday" },
  { text: "Thank you for the patience you've shown me in the places where I'm still growing.", category: "gratitude" },
  { text: "The fullness of your laugh when something genuinely catches you — I could listen to it all day.", category: "joy" },
  { text: "You are the most capable person I know in the moments that require it.", category: "strength" },
  { text: "The home you've made for our kids is something they'll feel the shape of their whole lives.", category: "family" },
  { text: "I catch myself looking at you and thinking you are everything all at once.", category: "beauty" },
  { text: "You don't perform kindness — you just are kind. There's no gap between who you are and how you act.", category: "character" },
  { text: "Loving you has been one of the defining experiences of my life and I'm grateful for every part of it.", category: "devotion" },
  { text: "You find the signal in the noise every time. That's not luck — that's a trained and careful mind.", category: "mind" },
  { text: "You've processed hard things with honesty instead of avoidance. That's the hard path and you took it.", category: "resilience" },
  { text: "The warmth you put into the world comes back around. I've watched it happen.", category: "warmth" },
  { text: "We're better together in every meaningful way. That's rare and I don't take it for granted.", category: "partnership" },
  { text: "You have done things that required real courage. I haven't forgotten them.", category: "admiration" },
  { text: "You said the exact right thing at the exact right moment and I didn't have words for how grateful I was.", category: "tenderness" },
  { text: "You find the comedy in our chaos and that might be what keeps us sane.", category: "humor" },
  { text: "You've gotten better at letting things be what they are instead of what you need them to be. That's hard-won wisdom.", category: "wisdom" },
  { text: "You've grown into yourself — not away from it. That's a direction worth keeping.", category: "growth" },
  { text: "You are the stability at the center of everything I love about my life.", category: "sanctuary" },
  { text: "The way you pour into people — it will outlive you in every person you've touched.", category: "legacy" },
  { text: "You're present in a way that feels like a choice, not a default. I notice that.", category: "presence" },
  { text: "You handled something hard today and still showed up for dinner. I see what that costs.", category: "everyday" },
  { text: "Thank you for building a life with me that feels like we meant to.", category: "gratitude" },
  { text: "Your joy doesn't need an occasion. It just shows up. That's a generosity of spirit.", category: "joy" },
  { text: "You adapt without losing yourself. That's a harder skill than it looks.", category: "strength" },
  { text: "You let our kids see you be human. That's going to matter more than the times you got it right.", category: "family" },
  { text: "You have a face that I could look at indefinitely and not get tired of. I mean that literally.", category: "beauty" },
  { text: "You are who you say you are. In every room, with every person. That's integrity.", category: "character" },
  { text: "Being loved by you is one of the best things that has ever happened to me.", category: "devotion" },
  { text: "You process things out loud when you need to and quietly when you need to. You know yourself well.", category: "mind" },
  { text: "You carry the weight of caring without letting it crush what makes you warm. That's hard to sustain.", category: "resilience" },
  { text: "You make people feel like they belong wherever you are. That is an act of love repeated daily.", category: "warmth" },
  { text: "You are the person I want next to me in the best moments and the worst ones. It's always you.", category: "partnership" },
  { text: "You've built real things — in yourself, in our family, in the people around you — through real effort.", category: "admiration" },
  { text: "The way you look at me sometimes — like you still see something worth looking at — I feel it.", category: "tenderness" },
  { text: "You brought levity to something that needed exactly that. You know when laughter is the answer.", category: "humor" },
  { text: "You've learned to separate what's urgent from what matters. Most people never do.", category: "wisdom" },
  { text: "You've become someone who makes it look effortless — but I've seen the effort. I respect both.", category: "growth" },
  { text: "You make ordinary life feel like something worth living, not just surviving.", category: "sanctuary" },
  { text: "The version of you that our kids will carry into the world — I'm already proud of it.", category: "legacy" },
  { text: "You have a way of slowing time down just by being still.", category: "presence" },
  { text: "You put gas in my car without telling me. I noticed it on a hard morning and I won't forget that.", category: "everyday" },
  { text: "Thank you for doing the emotional heavy lifting with grace when I couldn't match it.", category: "gratitude" },
  { text: "You get genuinely excited about good things and that excitement spreads. People love being near it.", category: "joy" },
  { text: "You face uncertainty with a steadiness that I lean on without always knowing I am.", category: "strength" },
  { text: "The consistency you bring to loving our family — every day, not just the good ones — is everything.", category: "family" },
  { text: "I find you more beautiful now than I did when I first thought you were beautiful.", category: "beauty" },
  { text: "You could have taken easier roads. You chose the ones that meant something.", category: "character" },
  { text: "I chose you then. I choose you now. I'll choose you again. That part doesn't change.", category: "devotion" },
  { text: "The way you hold complexity without demanding resolution — that's an intellectual maturity I deeply respect.", category: "mind" },
  { text: "You don't perform resilience. You just actually are resilient. Day after day.", category: "resilience" },
  { text: "You give warmth freely to people who've done nothing to earn it yet. That's generosity of spirit.", category: "warmth" },
  { text: "Everything works better when we're working together. That's not an accident — that's us.", category: "partnership" },
  { text: "You are the person I most want to become more like.", category: "admiration" },
  { text: "You gave me the kind of comfort this week that I couldn't have asked for because I didn't know I needed it.", category: "tenderness" },
  { text: "You make the hard thing funny without minimizing it. That's a sophisticated instinct.", category: "humor" },
  { text: "You've figured out what actually matters and let go of a lot of what doesn't. That kind of clarity is earned.", category: "wisdom" },
  { text: "You've grown toward the hard things, not away from them. That's the kind of growth that changes you.", category: "growth" },
  { text: "There is nowhere I'd rather land at the end of the day.", category: "sanctuary" },
  { text: "The story you're living is already shaping the stories of the people who come after you.", category: "legacy" },
  { text: "The quality of your attention when it's on me is one of the most remarkable things I've felt.", category: "presence" },
  { text: "You made a week that should have been a disaster manageable. Without fanfare. Just by handling it.", category: "everyday" },
  { text: "Thank you for making me feel like myself when I'd lost track of who that was.", category: "gratitude" },
  { text: "The way you celebrate good things — without hedging or minimizing — is something I want to be more like.", category: "joy" },
  { text: "You've carried the load without making anyone feel guilty for not carrying more. That's strength and grace at once.", category: "strength" },
  { text: "You are the reason this family knows what love looks like in practice and not just in words.", category: "family" },
  { text: "There is something quietly stunning about you on an ordinary day. I notice it more than I say.", category: "beauty" },
  { text: "You are honest without being brutal. That's a difficult calibration and you do it well.", category: "character" },
  { text: "The years have made me love you more, not less. I didn't know that was possible before you.", category: "devotion" },
  { text: "You draw on things other people would have forgotten. Your mind retains what matters.", category: "mind" },
  { text: "You've sat with things that had no resolution and waited them out with grace. That's a rare capacity.", category: "resilience" },
  { text: "People are better in your presence. I've watched it happen so many times I've lost count.", category: "warmth" },
  { text: "You hold your half of this without needing to be recognized for it. I recognize it.", category: "partnership" },
  { text: "There's a version of you that comes out when you're in your element that I think about long after.", category: "admiration" },
  { text: "You stayed up late to hear me out. You didn't need to. You wanted to. I know the difference.", category: "tenderness" },
  { text: "You've taught me that humor is a form of hope. I believe that now because of you.", category: "humor" },
  { text: "You've learned when to let someone else be right. That might be the hardest wisdom of all.", category: "wisdom" },
  { text: "You keep investing in who you're becoming. That's not easy alongside everything else you carry.", category: "growth" },
  { text: "Being with you is the most uncomplicated form of peace I've found.", category: "sanctuary" },
  { text: "What you're building here — the love, the safety, the values — will outlast everything else.", category: "legacy" },

  // ── Final 20 ─────────────────────────────────────────────────────────────
  { text: "You show up the same way whether anyone is watching or not. That's who you actually are.", category: "character" },
  { text: "You make the people you love feel like they're enough. That's one of the most important things a person can do.", category: "warmth" },
  { text: "I never have to wonder where I stand with you. That kind of clarity is a gift.", category: "devotion" },
  { text: "You carry our history with care. The things we've been through — you hold them gently.", category: "sanctuary" },
  { text: "The way you remember what people care about — it's not a trick, it's love. Real love.", category: "tenderness" },
  { text: "You are the kind of person that makes other people want to be better. I'm one of them.", category: "legacy" },
  { text: "You've never made me feel small. Not once. I don't take that for granted.", category: "partnership" },
  { text: "You walk into hard conversations instead of around them. That takes more courage than it looks like.", category: "strength" },
  { text: "The way you light up around the people you love — I could watch it all day.", category: "joy" },
  { text: "You've forgiven things that deserved forgiveness and held lines that needed holding. You know the difference.", category: "wisdom" },
  { text: "There's a groundedness to you that I've come to rely on more than I've ever said.", category: "presence" },
  { text: "You turned an ordinary evening into something I'll remember for years. You do that without trying.", category: "everyday" },
  { text: "Thank you for being the kind of partner who makes me want to show up as my best self.", category: "gratitude" },
  { text: "You've grown through things that would have defined other people. You let them shape you instead.", category: "growth" },
  { text: "The way you parent — with patience, with intention — I watch and I learn.", category: "family" },
  { text: "Something about the way you look when you're thinking — just quietly working something out — I find it beautiful.", category: "beauty" },
  { text: "You are sharper, wiser, and more yourself than the day I met you. All of that is attractive.", category: "admiration" },
  { text: "You make hard things feel less permanent. That's one of the most powerful things you give me.", category: "resilience" },
  { text: "The way your mind lands on exactly the right thing at exactly the right time — I trust it completely.", category: "mind" },
  { text: "You have made this one life feel like more than enough. That's everything.", category: "sanctuary" },
];
